version: '2'
services:
  web:
    image: steveortiz/chesstoolkitdemo:latest
    environment:
      RAILS_ENV: production
      DATABASE_HOST: db
      SECRET_KEY_BASE:
    ports:
      - "80:3000"
    links:
      - db
    volumes:
      - ./logs:/usr/src/app/log
    restart: always
  db:
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: sample_chess_api
      MYSQL_DATABASE: sample_chess_api
      MYSQL_USER: sample_chess_api
      MYSQL_PASSWORD: sample_chess_api
    restart: always
volumes:
  db_data:
